name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        
    - name: Build and deploy frontend
      working-directory: frontend
      run: |
        cd frontend
        npm ci
        npm run build
        # 배포 명령을 추가하세요. (예: AWS S3로 업로드)
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install backend dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd backend
        cd app
        
    - name: Build and deploy backend
      working-directory: backend
      env:
        FLASK_APP: app.py
      run: |
        flask build  # 필요한 경우 빌드 명령을 수정하세요.
        flask run --host=0.0.0.0  # 필요한 경우 실행 명령을 수정하세요.
