name: docker build and push to hub - frontend

on:
  workflow_call:
    inputs:
      dockerhub-username:
        required: true
        type: string
      dockerhub-token:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name : Build Docker Image & Push to Docker Hub
      run: |
        docker build ./frontend -t ai-drawing-test/frontend
        docker tag ai-drawing-test/frontend chaeeerish/ai-drawing-test-frontend
        docker push chaeeerish/ai-drawing-test-frontend
