name: Stop Jenkins Build

on:
  workflow_call:
    secrets:
      jenkins_url:
        required: true
      jenkins-api-token:
        required: true
      build_name:
        required: true

jobs:
  stop_jenkins_build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Stop Jenkins Build - frontend server
        env:
          JENKINS_URL: ${{ secrets.jenkins_url }}
          JENKINS_TOKEN: ${{ secrets.jenkins-api-token }}
          JOB_NAME: frontend-server-run
        run: |
          # Jenkins 빌드를 중단시키는 REST API 호출을 수행합니다.
          curl -X POST -u "${JENKINS_TOKEN}:" "${JENKINS_URL}/job/${JOB_NAME}/lastBuild/stop"

  stop_jenkins_build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Stop Jenkins Build - backend server
        env:
          JENKINS_URL: ${{ secrets.jenkins_url }}
          JENKINS_TOKEN: ${{ secrets.jenkins-api-token }}
          JOB_NAME: backend-server-run
        run: |
          # Jenkins 빌드를 중단시키는 REST API 호출을 수행합니다.
          curl -X POST -u "${JENKINS_TOKEN}:" "${JENKINS_URL}/job/${JOB_NAME}/lastBuild/stop"
