name: main workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-frontend-docker:
    uses: ./.github/workflows/frontend-docker.yml
    with:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  call-workflow-backend-docker:
    uses: ./.github/workflows/backend-docker.yml
    with:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  call-workflow-jenkins-build-trigger:
    uses: ./.github/workflows/jenkins-build-trigger.yml  
    with:
      webhook-url: ${{ secrets.WEBHOOK_URL }}
      jenkins-api-token: ${{ secrets.JENKINS_API_TOKEN }}